### ISSUE TITLE
office=yes not accepted as feature tag

### ISSUE THREAD

**Issue by johsin18** [geofabrik/osmi_simple_views#1]
Respective nodes are shown as no_feature_tag_nodes, while office=yes seems to be a valid feature tag, as per
https://wiki.openstreetmap.org/wiki/Tag:office%3Dyes

**Comment by Nakaner** [comment]
Sorry, I am aware of that but I will not support `office=yes` because this layer should serve as a assistance tool to find data uploaded by [spammers](https://lists.openstreetmap.org/pipermail/talk-us/2018-March/018399.html). `office=yes` is an invitation for them to dump their data into OSM without investing the necessary time to find a more suitable tag. In difference to any other `office=*`, `office=yes` is of nearly no value for data consumers.

**Comment by johsin18** [comment]
Combined with a name, office=yes is helpful IMHO. For many types of offices, there is no suitable value available. Should I rather create a new one then? Otherwise we are stuck with false positives.

**Comment by Nakaner** [comment]
There is a rule in OSM which is called [Any tags you like](https://wiki.openstreetmap.org/wiki/Any_tags_you_like). Applied on this use case, it means that you can just invent new values for `office=*` if you don't find an appropriate one.

**Comment by johsin18** [comment]
okay then
